### ISSUE TITLE
Link to GACS guidelines does not resolve

### ISSUE THREAD

**Issue by tombaker** [agrisemantics/website#8]
The website for the [GACS Quality Improvement project](https://agrisemantics.github.io/gacs-qip/), which holds the maintenance guidelines for GACS (editable on the [backend Github repo](https://github.com/agrisemantics/gacs-qip)) is not accessible via the agrisemantics.org address https://agrisemantics.org/gacs-qip/ (gets 404) .

The guidelines are currently available at https://agrisemantics.github.io/gacs-qip/ .

I see advantages to keeping the content in a separate Github repo (e.g., can authorize contributors to the guidelines without giving them access to the main agrisemantics.org repo), but since the guidelines are most likely not widely linked, the repo could be renamed (e.g., `gacs_guidelines` instead of `gacs-qip`).  [Renaming a Github repo](https://help.github.com/en/articles/renaming-a-repository) is easy.

**Comment by brandonnodnarb** [comment]
@tombaker, are you ok with me copying the qip md files over to the site instead of trying to sort out where the redirect is failing?  

We should probably migrate all the non-sensitive content from the original gacs-wg repo as well as the qip repo to their own repos under the current GACS  "institution", but these should probably be separate issues.

**Comment by tombaker** [comment]
I can't say re: agrisemantics.org.  The bigger issue is: What is "Agrisemantics"?  Does it really exist as an entity?  Or is it currently just an umbrella for GACS?  Or are the VEST registry and AgroPortal claimed as being under the Agrisemantics umbrella?  Or is Agrisemantics just a concept?

**Comment by brandonnodnarb** [comment]
>  The bigger issue is: What is "Agrisemantics"?
Sure, but that's a separate issue.  I don't know what Agrisemantics is at this point.  I *think* vest is intended to be under agrisemantics (the URL for the project is vest.agrisemantics.org).  I have no idea about AgroPortal.

The only reason agrisemantics.org even makes sense, at least to me, is because GACS uses id.agrisemantics.org as the URI scheme.  Which means agrisemantics.org should somehow be a thing.   This decision was before my time.  I do not know the rational for this, or why, for example, PURLs, id.gacs.ag, or any number of other IDs or services weren't used.

This is what we have so I'm trying to make lemonade.

**Comment by brandonnodnarb** [comment]
files copied over.  Good content in here, but the issue, as originally stated, has been addressed.
